import { Report } from './types'

export const MOCK_REPORTS: Report[] = [
  // ── OBRAS PARALIZADAS ──────────────────────────────────────────────────
  {
    id: 'mock-obra-1',
    type: 'denuncia',
    category: 'obra',
    title: 'Obra de pistas paralizada 8 meses en Miraflores',
    description: 'Av. Larco cuadra 8: contrato por S/. 2.4M, avance declarado 60% pero sin movimiento desde octubre.',
    latitude: -12.1199,
    longitude: -77.0287,
    address: 'Av. Larco 841, Miraflores',
    photoUrl: 'https://placehold.co/400x300/F59E0B/white?text=Obra',
    status: 'pending_response',
    supportCount: 87,
    collectiveRequestSent: true,
    responsibleEntity: 'Municipalidad de Miraflores',
    responsibleChannel: 'Gerencia de Obras Públicas — Expediente N° 2024-14892',
    stateData: {
      infobras: { found: true, source: 'INFOBRAS', code: 'INF-2024-14892', budget: 2400000, progressPct: 60, daysWithoutMovement: 243, contractor: 'Constructora Vial Andina SAC' },
      mef: { found: true, source: 'MEF/SIAF', assigned: 2400000, executed: 1440000, executionPct: 60 },
    },
    createdAt: '2025-11-15T09:22:00Z',
  },
  {
    id: 'mock-obra-2',
    type: 'denuncia',
    category: 'obra',
    title: 'Puente peatonal sin terminar en SJL — 14 meses',
    description: 'Cruce de Av. Próceres de la Independencia con Av. Las Flores. Estructura a 40% de avance. Sin trabajadores desde enero.',
    latitude: -11.9802,
    longitude: -77.0021,
    address: 'Av. Próceres 1240, San Juan de Lurigancho',
    photoUrl: 'https://placehold.co/400x300/F59E0B/white?text=Puente',
    status: 'active',
    supportCount: 134,
    collectiveRequestSent: true,
    responsibleEntity: 'Municipalidad de San Juan de Lurigancho',
    responsibleChannel: 'Contraloría General — Servicio de Atención Ciudadana',
    stateData: {
      infobras: { found: true, source: 'INFOBRAS', code: 'INF-2024-09123', budget: 890000, progressPct: 40, daysWithoutMovement: 178, contractor: 'Obras Civiles del Perú EIRL' },
    },
    createdAt: '2025-10-02T14:33:00Z',
  },
  {
    id: 'mock-obra-3',
    type: 'denuncia',
    category: 'obra',
    title: 'Colegio en construcción sin avance — Los Olivos',
    description: 'IE 2054 en Av. Universitaria. Presupuesto S/. 3.1M ejecutado al 35% en 18 meses.',
    latitude: -11.9943,
    longitude: -77.0690,
    address: 'Av. Universitaria 4200, Los Olivos',
    photoUrl: 'https://placehold.co/400x300/F59E0B/white?text=Colegio',
    status: 'active',
    supportCount: 213,
    collectiveRequestSent: true,
    responsibleEntity: 'MINEDU — PRONIED',
    responsibleChannel: 'Contraloría — Sistema de Control Gubernamental',
    stateData: {
      infobras: { found: true, source: 'INFOBRAS', code: 'INF-2023-77412', budget: 3100000, progressPct: 35, daysWithoutMovement: 312 },
      mef: { found: true, source: 'MEF/SIAF', assigned: 3100000, executed: 1085000, executionPct: 35 },
    },
    createdAt: '2024-12-08T08:15:00Z',
  },

  // ── PROPUESTAS ──────────────────────────────────────────────────────────
  {
    id: 'mock-prop-1',
    type: 'propuesta',
    category: 'propuesta',
    title: 'Ciclovía en Av. Arequipa — Miraflores a San Isidro',
    description: 'Propuesta de ciclovía segregada de 4.2 km conectando ambos distritos. 890 vecinos firmaron el petitorio.',
    latitude: -12.1055,
    longitude: -77.0321,
    address: 'Av. Arequipa (tramo Miraflores–San Isidro)',
    photoUrl: 'https://placehold.co/400x300/8B5CF6/white?text=Ciclovía',
    status: 'active',
    supportCount: 892,
    collectiveRequestSent: true,
    responsibleEntity: 'Municipalidad Metropolitana de Lima',
    responsibleChannel: 'Gerencia de Transporte Urbano — Mesa de Partes Virtual',
    createdAt: '2025-08-20T11:00:00Z',
  },
  {
    id: 'mock-prop-2',
    type: 'propuesta',
    category: 'propuesta',
    title: 'Parque con zona de juegos en VES Sector 3',
    description: 'El terreno municipal de 2,800 m² en Av. Pastor Sevilla lleva 5 años sin uso. Vecinos proponen parque infantil con iluminación LED.',
    latitude: -12.2140,
    longitude: -76.9441,
    address: 'Av. Pastor Sevilla 890, Villa El Salvador',
    photoUrl: 'https://placehold.co/400x300/8B5CF6/white?text=Parque',
    status: 'active',
    supportCount: 341,
    collectiveRequestSent: false,
    responsibleEntity: 'Municipalidad de Villa El Salvador',
    createdAt: '2025-09-14T16:40:00Z',
  },
  {
    id: 'mock-prop-3',
    type: 'propuesta',
    category: 'propuesta',
    title: 'Alumbrado solar en pasajes de Comas',
    description: 'Pasajes Jr. Las Flores y Jr. Los Pinos sin luz desde 2022. Se propone instalación de 18 paneles solares con iluminación LED.',
    latitude: -11.9360,
    longitude: -77.0511,
    address: 'Jr. Las Flores 340, Comas',
    photoUrl: 'https://placehold.co/400x300/8B5CF6/white?text=Solar',
    status: 'pending_response',
    supportCount: 156,
    collectiveRequestSent: true,
    responsibleEntity: 'Municipalidad de Comas — OSINERGMIN',
    createdAt: '2025-11-03T10:25:00Z',
  },

  // ── BASURA ──────────────────────────────────────────────────────────────
  {
    id: 'mock-bas-1',
    type: 'denuncia',
    category: 'basura',
    title: 'Botadero ilegal bajo el puente de Breña',
    description: 'Acumulación de 3 toneladas de desmonte y residuos sólidos bajo el puente de Av. Brasil. Genera ratas y mal olor.',
    latitude: -12.0601,
    longitude: -77.0498,
    address: 'Av. Brasil s/n (bajo puente), Breña',
    photoUrl: 'https://placehold.co/400x300/84CC16/white?text=Basura',
    status: 'active',
    supportCount: 67,
    collectiveRequestSent: false,
    responsibleEntity: 'Municipalidad de Breña',
    createdAt: '2025-12-01T07:45:00Z',
  },
  {
    id: 'mock-bas-2',
    type: 'denuncia',
    category: 'basura',
    title: 'Recojo de basura suspendido 3 semanas en Ate',
    description: 'Zona industrial de Ate sin recojo desde el 10 de noviembre. Containers desbordados generan foco infeccioso.',
    latitude: -12.0312,
    longitude: -76.9188,
    address: 'Av. Los Frutales 1200, Ate',
    photoUrl: 'https://placehold.co/400x300/84CC16/white?text=Residuos',
    status: 'active',
    supportCount: 44,
    collectiveRequestSent: false,
    responsibleEntity: 'Municipalidad de Ate',
    createdAt: '2025-11-29T09:10:00Z',
  },

  // ── AGUA ────────────────────────────────────────────────────────────────
  {
    id: 'mock-agua-1',
    type: 'denuncia',
    category: 'agua',
    title: 'Tubería rota con fuga hace 12 días en La Victoria',
    description: 'Cruce de Jr. Huánuco con Jr. Sebastián Barranca. Agua corriendo 24h/día. SEDAPAL notificado sin respuesta.',
    latitude: -12.0701,
    longitude: -77.0139,
    address: 'Jr. Huánuco cdra. 8, La Victoria',
    photoUrl: 'https://placehold.co/400x300/06B6D4/white?text=Agua',
    status: 'pending_response',
    supportCount: 28,
    collectiveRequestSent: false,
    responsibleEntity: 'SEDAPAL',
    responsibleChannel: 'SEDAPAL — Línea de Emergencias 317-8000',
    createdAt: '2025-12-10T15:30:00Z',
  },
  {
    id: 'mock-agua-2',
    type: 'denuncia',
    category: 'agua',
    title: 'Sin agua potable 5 días — San Martín de Porres',
    description: 'AA.HH. Santa Rosa de Lima sin servicio desde el lunes. 280 familias afectadas. Solo camión cisterna 2 veces/semana.',
    latitude: -12.0215,
    longitude: -77.0843,
    address: 'AA.HH. Santa Rosa de Lima, San Martín de Porres',
    photoUrl: 'https://placehold.co/400x300/06B6D4/white?text=Sin+Agua',
    status: 'active',
    supportCount: 189,
    collectiveRequestSent: true,
    responsibleEntity: 'SEDAPAL — Municipalidad de San Martín de Porres',
    createdAt: '2025-12-08T12:00:00Z',
  },

  // ── LUZ ─────────────────────────────────────────────────────────────────
  {
    id: 'mock-luz-1',
    type: 'denuncia',
    category: 'luz',
    title: '6 postes sin luz en Jr. Ancash, Cercado',
    description: 'Cuadras 14-17 del Jr. Ancash completamente oscuras desde el sismo de agosto. Aumento de robos en la zona.',
    latitude: -12.0491,
    longitude: -77.0286,
    address: 'Jr. Ancash cdras. 14-17, Cercado de Lima',
    photoUrl: 'https://placehold.co/400x300/F59E0B/white?text=Sin+Luz',
    status: 'active',
    supportCount: 53,
    collectiveRequestSent: false,
    responsibleEntity: 'Municipalidad de Lima — Luz del Sur',
    createdAt: '2025-11-20T20:15:00Z',
  },

  // ── AMBIENTE ─────────────────────────────────────────────────────────────
  {
    id: 'mock-amb-1',
    type: 'denuncia',
    category: 'ambiente',
    title: 'Fábrica emite humo negro en Villa El Salvador',
    description: 'Planta industrial en Av. Separadora Industrial. Humo negro visible desde las 6am. Vecinos con afecciones respiratorias.',
    latitude: -12.2101,
    longitude: -76.9398,
    address: 'Av. Separadora Industrial 1440, Villa El Salvador',
    photoUrl: 'https://placehold.co/400x300/10B981/white?text=Contaminación',
    status: 'pending_response',
    supportCount: 312,
    collectiveRequestSent: true,
    responsibleEntity: 'OEFA — Organismo de Evaluación y Fiscalización Ambiental',
    responsibleChannel: 'OEFA — Denuncia Ambiental: denuncias@oefa.gob.pe',
    stateData: {
      oefa: { found: true, source: 'OEFA', previousInspections: 3, lastInspectionDate: '2024-03-15' },
    },
    createdAt: '2025-10-28T08:00:00Z',
  },

  // ── PISTA ────────────────────────────────────────────────────────────────
  {
    id: 'mock-pista-1',
    type: 'denuncia',
    category: 'pista',
    title: 'Bache de 2m de diámetro en Av. Tomás Marsano',
    description: 'Peligroso bache en carril derecho de Av. Tomás Marsano altura km 3.5. Ya hubo 4 accidentes este mes.',
    latitude: -12.1380,
    longitude: -77.0023,
    address: 'Av. Tomás Marsano km 3.5, Surco',
    photoUrl: 'https://placehold.co/400x300/6366F1/white?text=Bache',
    status: 'active',
    supportCount: 78,
    collectiveRequestSent: false,
    responsibleEntity: 'Municipalidad de Santiago de Surco',
    createdAt: '2025-12-05T11:40:00Z',
  },
  {
    id: 'mock-pista-2',
    type: 'denuncia',
    category: 'pista',
    title: 'Vereda destruida por raíces en Pueblo Libre',
    description: 'Jr. Sucre cuadra 4: veredas levantadas por raíces de árboles municipales. Adultos mayores han sufrido caídas.',
    latitude: -12.0758,
    longitude: -77.0631,
    address: 'Jr. Sucre 420, Pueblo Libre',
    photoUrl: 'https://placehold.co/400x300/6366F1/white?text=Vereda',
    status: 'resolved',
    supportCount: 34,
    collectiveRequestSent: false,
    responsibleEntity: 'Municipalidad de Pueblo Libre',
    createdAt: '2025-09-18T14:20:00Z',
  },

  // ── PARQUE ────────────────────────────────────────────────────────────────
  {
    id: 'mock-parque-1',
    type: 'denuncia',
    category: 'parque',
    title: 'Parque Leoncio Prado abandonado — Lince',
    description: 'Juegos oxidados peligrosos, pasto sin cortar 2 meses, luminarias rotas. Área de 1,200m² en deterioro.',
    latitude: -12.0858,
    longitude: -77.0309,
    address: 'Parque Leoncio Prado, Lince',
    photoUrl: 'https://placehold.co/400x300/22C55E/white?text=Parque',
    status: 'active',
    supportCount: 91,
    collectiveRequestSent: false,
    responsibleEntity: 'Municipalidad de Lince',
    createdAt: '2025-11-12T09:55:00Z',
  },

  // ── SEGURIDAD ─────────────────────────────────────────────────────────────
  {
    id: 'mock-seg-1',
    type: 'denuncia',
    category: 'seguridad',
    title: 'Zona de alta incidencia de robos — Jr. Ica, Barranco',
    description: '7 robos al paso reportados en el mes en Jr. Ica cuadras 2-5. Zona oscura sin cámaras de vigilancia.',
    latitude: -12.1425,
    longitude: -77.0201,
    address: 'Jr. Ica cdras. 2-5, Barranco',
    photoUrl: 'https://placehold.co/400x300/EF4444/white?text=Seguridad',
    status: 'active',
    supportCount: 143,
    collectiveRequestSent: true,
    responsibleEntity: 'Municipalidad de Barranco — PNP Comisaría de Barranco',
    responsibleChannel: 'PNP Barranco: 477-1021 — Serenazgo: 477-6565',
    createdAt: '2025-12-02T22:10:00Z',
  },
]
